In [1]:
import numpy as np
import pandas as pd
from sklearn import tree

In [2]:
covidDataset = pd.read_csv('covid.csv',delimiter=',',header=0)

In [3]:
covidDataset.head()

Id  Confirmed  Deaths  ...  New deaths  New recovered                 Region
0   1          0       0  ...           0              0  Eastern Mediterranean
1   2          0       0  ...           0              0                 Europe
2   3          0       0  ...           0              0                 Africa
3   4          0       0  ...           0              0                 Europe
4   5          0       0  ...           0              0                 Africa

[5 rows x 9 columns]

In [4]:
covidDataset["Region"] = pd.factorize(covidDataset.Region)[0]

In [6]:
covidDataset.head()

Id  Confirmed  Deaths  ...  New deaths  New recovered  Region
0   1          0       0  ...           0              0       0
1   2          0       0  ...           0              0       1
2   3          0       0  ...           0              0       2
3   4          0       0  ...           0              0       1
4   5          0       0  ...           0              0       2

[5 rows x 9 columns]

In [7]:
covidDataset = covidDataset.drop(labels="Id",axis=1)

In [8]:
print(covidDataset)

    Confirmed  Deaths  Recovered  ...  New deaths  New recovered  Region
0           0       0          0  ...           0              0       0
1           0       0          0  ...           0              0       1
2           0       0          0  ...           0              0       2
3           0       0          0  ...           0              0       1
4           0       0          0  ...           0              0       2
..        ...     ...        ...  ...         ...            ...     ...
95          0       0          0  ...           0              0       1
96          0       0          0  ...           0              0       0
97          0       0          0  ...           0              0       2
98          0       0          0  ...           0              0       2
99          0       0          0  ...           0              0       0

[100 rows x 8 columns]


In [9]:
covidDataset = covidDataset.to_numpy()

In [10]:
print(covidDataset)

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   4]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   5]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   5]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   4]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   5]
 [  0   0   0   0   

In [11]:
dataTraining = np.concatenate((covidDataset[0:40, :], covidDataset[50:90, :]),axis=0)
dataTesting = np.concatenate((covidDataset[40:50, :], covidDataset[90:100, :]),axis=0)

In [12]:
print(dataTesting)
len(dataTesting)

[[0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 3]
 [0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 4]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0]]


20

In [13]:
print(dataTraining)
len(dataTraining)

[[  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   4]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   5]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   5]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   3]
 [  0   0   0   0   0   0   0   4]
 [  0   0   0   0   0   0   0   1]
 [  0   0   0   0   0   0   0   2]
 [  0   0   0   0   0   0   0   5]
 [  0   0   0   0   

80

In [14]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]

In [15]:
model = tree.DecisionTreeClassifier()

In [16]:
model = model.fit(inputTraining, labelTraining)

In [17]:
hasilPrediksi = model.predict(inputTesting)

In [18]:
print("Label sebenarnya ",labelTesting)
print("Hasil prediksi ",hasilPrediksi)

Label sebenarnya  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Hasil prediksi  [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [19]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()

In [20]:
print("Prediksi benar: ", prediksiBenar, " data")
print("Prediksi salah: ", prediksiSalah, " data")
print("Akurasi: ",prediksiBenar/(prediksiBenar+prediksiSalah)*100,"%")

Prediksi benar:  20  data
Prediksi salah:  0  data
Akurasi:  100.0 %
