In [143]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [144]:
dataset = pd.read_csv('data2.csv')
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:, -1].values

In [145]:
print(x)

[['hendry' 30.0 100000.0]
 ['permana' 27.0 230000.0]
 ['hendry' 40.0 400000.0]
 ['permana' 36.0 140000.0]
 ['farizh' 35.0 190000.0]
 ['verom' nan 400000.0]
 ['farizh' 60.0 nan]
 ['farah' 20.0 50000.0]
 ['verom' 27.0 140000.0]
 ['farah' 20.0 50000.0]]


In [146]:
print(y)

['yes' 'no' 'yes' 'yes' 'yes' 'no' 'yes' 'no' 'no' 'no']


In [147]:
from sklearn.impute import  SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [148]:
from sklearn.compose import  ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [149]:
print(x)

[[0.0 0.0 1.0 0.0 0.0 30.0 100000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 230000.0]
 [0.0 0.0 1.0 0.0 0.0 40.0 400000.0]
 [0.0 0.0 0.0 1.0 0.0 36.0 140000.0]
 [0.0 1.0 0.0 0.0 0.0 35.0 190000.0]
 [0.0 0.0 0.0 0.0 1.0 32.77777777777778 400000.0]
 [0.0 1.0 0.0 0.0 0.0 60.0 188888.88888888888]
 [1.0 0.0 0.0 0.0 0.0 20.0 50000.0]
 [0.0 0.0 0.0 0.0 1.0 27.0 140000.0]
 [1.0 0.0 0.0 0.0 0.0 20.0 50000.0]]


In [150]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [151]:
print(y)

[1 0 1 1 1 0 1 0 0 0]


In [152]:
from sklearn.model_selection import  train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=1)

In [153]:
print(x_train)

[[0.0 1.0 0.0 0.0 0.0 60.0 188888.88888888888]
 [0.0 1.0 0.0 0.0 0.0 35.0 190000.0]
 [0.0 0.0 1.0 0.0 0.0 30.0 100000.0]
 [0.0 0.0 0.0 1.0 0.0 36.0 140000.0]
 [0.0 0.0 0.0 1.0 0.0 27.0 230000.0]
 [1.0 0.0 0.0 0.0 0.0 20.0 50000.0]
 [0.0 0.0 0.0 0.0 1.0 27.0 140000.0]
 [0.0 0.0 0.0 0.0 1.0 32.77777777777778 400000.0]]


In [154]:
print(x_test)

[[0.0 0.0 1.0 0.0 0.0 40.0 400000.0]
 [1.0 0.0 0.0 0.0 0.0 20.0 50000.0]]


In [155]:
print(y_train)

[1 1 1 1 0 0 0 0]


In [156]:
print(y_test)

[1 0]


In [157]:
from sklearn.preprocessing import  StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [158]:
print(x_train)

[[0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 2.384350267392578
  0.09167568474886666]
 [0.0 1.0 0.0 -0.5773502691896258 -0.5773502691896258 0.13731860178700717
  0.10295884594872733]
 [0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258
  -0.31208773133410694 -0.8109772112399767]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 0.22719986841123
  -0.40478340804499713]
 [0.0 0.0 0.0 1.7320508075688774 -0.5773502691896258 -0.5817315312067755
  0.509152649143707]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 -1.2109003975763353
  -1.3187194652337013]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774 -0.5817315312067755
  -0.40478340804499713]
 [0.0 0.0 0.0 -0.5773502691896258 1.7320508075688774
  -0.062417546266821264 2.23547631272237]]


In [159]:
print(x_test)

[[0.0 0.0 1.0 -0.5773502691896258 -0.5773502691896258 0.5867249349081213
  2.23547631272237]
 [1.0 0.0 0.0 -0.5773502691896258 -0.5773502691896258 -1.2109003975763353
  -1.3187194652337013]]
